# Generated by Django 2.2.6 on 2020-05-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozetka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_promo_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
