# Generated by Django 2.2.6 on 2020-05-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozetka', '0002_auto_20200515_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cheaper_price',
            field=models.FloatField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.FloatField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.FloatField(blank=True, default='', null=True),
        ),
    ]
