# Generated by Django 2.2.6 on 2020-05-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozetka', '0005_auto_20200517_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
