# Generated by Django 2.2.6 on 2020-05-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozetka', '0006_auto_20200524_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
